// src/application/application.module.ts
import { Module } from '@nestjs/common'
import { InfrastructureModule } from '../infrastructure/infrastructure.module'
import {
  RegisterAdminUseCase,
  RegisterStudentUseCase,
  LoginAdminUseCase,
  LoginStudentUseCase,
  RefreshTokenUseCase,
  LogoutUseCase,
  CreateDocumentUseCase,
  CreateQuestionImageUseCase,
  CreateSolutionImageUseCase,
  CreateMediaImageUseCase,
  CreateImageUseCase,
  CreateRoleUseCase,
  RollbackUseCase,
  GetAllStudentUseCase,
  UpdateStudentUseCase,
  UpdateAdminUseCase,
  UpdateUserUseCase,
  UpdateUserAvatarUseCase,
  GoogleOAuthAdminUseCase,
  GoogleOAuthStudentUseCase,
  SendVerificationEmailUseCase,
  VerifyEmailUseCase,
  FetchStudentFromApiUseCase,
  GetProfileStudentUseCase,
} from './use-cases'

@Module({
  imports: [InfrastructureModule],
  providers: [
    RegisterAdminUseCase,
    RegisterStudentUseCase,
    LoginAdminUseCase,
    LoginStudentUseCase,
    RefreshTokenUseCase,
    LogoutUseCase,
    CreateDocumentUseCase,
    CreateQuestionImageUseCase,
    CreateSolutionImageUseCase,
    CreateMediaImageUseCase,
    CreateImageUseCase,
    CreateRoleUseCase,
    RollbackUseCase,
    GetAllStudentUseCase,
    UpdateStudentUseCase,
    UpdateAdminUseCase,
    UpdateUserUseCase,
    UpdateUserAvatarUseCase,
    GoogleOAuthAdminUseCase,
    GoogleOAuthStudentUseCase,
    SendVerificationEmailUseCase,
    VerifyEmailUseCase,
    FetchStudentFromApiUseCase,
    GetProfileStudentUseCase,
  ],
  exports: [
    RegisterAdminUseCase,
    RegisterStudentUseCase,
    LoginAdminUseCase,
    LoginStudentUseCase,
    RefreshTokenUseCase,
    LogoutUseCase,
    CreateDocumentUseCase,
    CreateQuestionImageUseCase,
    CreateSolutionImageUseCase,
    CreateMediaImageUseCase,
    CreateImageUseCase,
    CreateRoleUseCase,
    RollbackUseCase,
    GetAllStudentUseCase,
    UpdateStudentUseCase,
    UpdateAdminUseCase,
    UpdateUserUseCase,
    UpdateUserAvatarUseCase,
    GoogleOAuthAdminUseCase,
    GoogleOAuthStudentUseCase,
    SendVerificationEmailUseCase,
    VerifyEmailUseCase,
    FetchStudentFromApiUseCase,
    GetProfileStudentUseCase,
  ],
})
export class ApplicationModule { }
