version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "070904"
      MYSQL_DATABASE: "beedatabase"
      MYSQL_USER: "duck"
      MYSQL_PASSWORD: "070904"
      TZ: "Asia/Ho_Chi_Minh"
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      # đổi 3307 nếu máy đã có MySQL; bind localhost để không lộ ra internet
      - "127.0.0.1:3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p070904", "-uduck"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  db_data:
